# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [3]:
import numpy as np

2. Create a null vector of size 10 

In [ ]:
np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [ ]:
arr1=np.arange(9,50)
arr1

4. Find the shape of previous array in question 3

In [ ]:
np.shape(arr1)

5. Print the type of the previous array in question 3

In [ ]:
type(arr1)

6. Print the numpy version and the configuration


In [ ]:
print(np.__version__)
print(np.show_config())

7. Print the dimension of the array in question 3


In [ ]:
arr1

8. Create a boolean array with all the True values

In [ ]:
bool_arr = np.random.choice(sample_arr, size=10)
print(bool_arr)

9. Create a two dimensional array




In [ ]:
arr2d = np.arange(30).reshape(6,5)
arr2d

10. Create a three dimensional array



In [ ]:
arr3d = np.arange(40).reshape(2,4,5)
arr3d

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [ ]:
Rev=arr1[::-1]
Rev

12. Create a null vector of size 10 but the fifth value which is 1 

In [ ]:
null=np.zeros(10)
null[4]=1
null

13. Create a 3x3 identity matrix

In [ ]:
matrix=np.identity(3)
matrix

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
print("---------")
float_arr = arr.astype(np.float)
float_arr.dtype

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [ ]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
Multiply = arr1 * arr2
Multiply

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [ ]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
Compar_arr = arr1+arr2
Compar_arr

17. Extract all odd numbers from arr with values(0-9)

In [ ]:
odd = np.arange(0,10 , 3)
odd

18. Replace all odd numbers to -1 from previous array

In [ ]:
odd [odd < -0]=-1
odd

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [ ]:
arr = np.arange()
arr [] 5 = 12
arr

20. Create a 2d array with 1 on the border and 0 inside

In [ ]:
d = np.ones((5,5))
d [1:-1,1:-1]=0
d

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [ ]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1][1]=12
arr2d

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0:1]=64
arr3d

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [ ]:
arr2d=np.arange(0,9).reshape(3,3)
print(arr2d)
arr2d[0,0]

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [ ]:
arr2d=np.arange(0,9).reshape(3,3)
print(arr2d)
arr2d[1,1]

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [ ]:
arr2d=np.arange(0,9).reshape(3,3)
arr2d
arr2d[0:,:2]

26. Create a 10x10 array with random values and find the minimum and maximum values

In [89]:
rand=np.random.random((10,10))
print(rand)
rand.min()
rand.max()
print("Min" ,rand.min(), "Max" ,rand.max())

[[0.19531405 0.29393842 0.84841329 0.1056575  0.03615202 0.20384074
  0.4366343  0.27839854 0.10725885 0.62254627]
 [0.84653381 0.15505648 0.01815822 0.00718194 0.2072812  0.05277113
  0.14086769 0.37720614 0.71501225 0.44262328]
 [0.04245414 0.24280955 0.19676336 0.99985064 0.20485375 0.44264356
  0.5277055  0.06478502 0.26148279 0.51919121]
 [0.83021228 0.54453255 0.83911156 0.07684614 0.82644001 0.79710144
  0.99134096 0.42129365 0.74954386 0.70103818]
 [0.06002266 0.38995039 0.19570832 0.22417553 0.76137083 0.81748198
  0.46955444 0.2360813  0.54804786 0.30473623]
 [0.63888837 0.46825297 0.77535836 0.95369237 0.92836431 0.63492611
  0.62912681 0.65720156 0.0340801  0.93160778]
 [0.57278781 0.17905216 0.50470895 0.24272263 0.64909584 0.59749308
  0.47798607 0.05317768 0.81034038 0.07826383]
 [0.1957081  0.85038646 0.77175001 0.6398215  0.996685   0.45062347
  0.10779008 0.9633504  0.57263259 0.46402063]
 [0.4619766  0.05776311 0.5671382  0.08262169 0.43885667 0.83221083
  0.92922575

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [4]:
arr1 = np.arange(0,4)
print(arr1)
arr2 = [1, 3, 4] 

# Common values between two arrays 
print("Common",np.intersect1d(arr1, arr2)) 


[0 1 2 3]
Common [1 3]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [12]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(np.in1d(a, b))

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [202]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names!='Will']


array([[ 1.17917687,  0.87774647, -1.45203136, -0.10606717],
       [ 0.84602615,  0.17324112, -0.51239208,  0.38184375],
       [ 1.71123559, -1.13023787, -0.27210186, -0.37230712],
       [-0.46896024,  0.80159093, -0.40806664,  0.16081549],
       [-0.55041108, -1.17240856,  0.29761093, -0.70322246]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [206]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[names!='Will''Joe']

array([[-1.77233632, -0.41762558, -0.08528334, -1.42628146],
       [ 1.24124849,  0.1573344 ,  0.23358173, -1.18370409],
       [-0.19733271,  0.72029487, -0.03045093, -0.77616828],
       [-2.42289742,  0.44875738,  0.02933833, -1.3464057 ],
       [ 1.58962953,  0.02718819, -0.87008403,  1.95924761],
       [-1.19602005, -0.60369145,  1.31726511, -0.5143264 ],
       [ 1.26218649, -1.66152233, -0.08635808, -0.94469785]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [23]:
arr2d=np.arange(1,16).reshape(5,3)
arr2d=arr2d.astype(np.float)
arr2d

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [29]:
arr1d= np.arange(1,17)
arr=arr1d.reshape(2,2,4)
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [38]:
np.swapaxes(arr, 2,1)

array([[[ 1,  5],
        [ 2,  6],
        [ 3,  7],
        [ 4,  8]],

       [[ 9, 13],
        [10, 14],
        [11, 15],
        [12, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [72]:
arr1=np.arange(10)
print(arr1/2)
arr1[ 0.5 < arr1/2 ] = 0
arr1

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [197]:
rand=np.random.random((6,2))
print(rand)

print("Max") 
rand.max()


[[0.20676003 0.01537697]
 [0.62643126 0.91651916]
 [0.9478785  0.14275856]
 [0.8073426  0.95346486]
 [0.16279108 0.49064161]
 [0.84374506 0.55582819]]
Max


0.9534648562159596

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [111]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [110]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
result = np.setdiff1d(a, b)
result

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [179]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
sampleArray_del=np.delete(sampleArray,1,1)
print(sampleArray_del)
arr=np.insert(sampleArray_del ,1, 10,axis=1)
print(arr)


[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[34 73]
 [82 12]
 [53 66]]
[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [185]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [189]:
matrix=np.arange(20)
print(matrix)
np.cumsum(matrix)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190], dtype=int32)