
# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
import numpy as np
arr1=np.arange(20)
print('Array1d', arr1)
arr2=arr1.reshape(4,5)
arr2

Array1d [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [28]:
a = np.arange(5)
b = np.arange(5)
np.vstack((a,b))


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [29]:
a = np.arange(5)
b = np.arange(5)
np.hstack((a,b))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [24]:
arr2d=np.arange(10).reshape(5,2)
arr2d
arr1d=arr2d.reshape(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [33]:
arr2d=np.arange(15).reshape(5,1,3)
print(arr2d)
arr1d=arr2d.reshape(15)
arr1d

[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]

 [[12 13 14]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [41]:
a=np.arange(15)
High_dem=a.reshape(5,1,3)
High_dem

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]],

       [[12, 13, 14]]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [51]:
a=np.arange(25).reshape(5,5)
print(a)
np.square(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [57]:
a=np.arange(30).reshape(5,6)
a
np.mean(a)

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [58]:
stan_dev=np.std(a)
stan_dev

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [59]:
np.median(a)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [63]:
np.transpose(a)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [65]:
arr=np.arange(16).reshape(4,4)
np.trace(arr)

30

## Question:13

### Find the determinant of the previous array in Q12?

In [67]:
np.linalg.det(arr)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [91]:
np.arange(96)
a=np.percentile(per,5)
b=np.percentile(per,95)
print('5th' ,a ,"95th", b )

5th 4.75 95th 90.25


## Question:15

### How to find if a given array has any null values?

In [70]:
np.isnan(np.nan)

True